<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>..\assets\Otacon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.17" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.17" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.17" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.17" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="IconPacks.Avalonia.FontAwesome" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Codec.Base\Codec.Base.csproj" />
    <ProjectReference Include="..\Codec.M2\Codec.M2.csproj" />
    <ProjectReference Include="..\Codec.Rendering\Codec.Rendering.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="..\assets\Otacon.ico" Link="Assets\Otacon.ico" />
  </ItemGroup>
  <Import Project="..\PublishApp.targets" />
</Project>