<Project>
  <PropertyGroup>
    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>$(SelfContained)</EnableCompressionInSingleFile>
    <RepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RepoRoot>
    <PublishDir>$(RepoRoot)publish\$(MSBuildProjectName)-$(Platform)-$(Configuration)-$(RuntimeIdentifier)\</PublishDir>
  </PropertyGroup>
  <Target Name="ExcludePdbFromPublish" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.pdb'" />
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.xml'" />
    </ItemGroup>
  </Target>
  <Target Name="RenamePublishExe" AfterTargets="Publish" Condition="Exists('$(PublishDir)$(AssemblyName).exe')">
    <Move SourceFiles="$(PublishDir)$(AssemblyName).exe" DestinationFiles="$(PublishDir)codec.exe" />
  </Target>
  <Target Name="ZipPublishOutput" AfterTargets="Publish">
    <PropertyGroup>
      <_ZipFileName>$(MSBuildProjectName)-$(Platform)-$(Configuration)-$(RuntimeIdentifier)-v$(Version).zip</_ZipFileName>
    </PropertyGroup>
    <ZipDirectory SourceDirectory="$(PublishDir)" DestinationFile="$(RepoRoot)publish\$(_ZipFileName)" Overwrite="true" />
  </Target>
</Project>
