<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SharedAssemblyProperties.props" />
  <PropertyGroup>
    <RootNamespace>Codec</RootNamespace>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/otac0n/Codec</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
    <PackageReference Include="MeltySynth" Version="2.4.1" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="VgmSharp" Version="0.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Codec.Base\Codec.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\florestan-subset.sf2" />
    <EmbeddedResource Include="Resources\florestan-subset.sf2" />
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>