// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("f8afc8f0-19bf-8a9b-5aaf-8ef0e6d46c59")]
[assembly: InternalsVisibleTo("Codec.Tests")]
