// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("e1f4a508-e2d3-4262-ae1c-8133a52be323")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Codec.Tests")]
