<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SharedAssemblyProperties.props" />
  <PropertyGroup>
    <RootNamespace>Codec</RootNamespace>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/otac0n/Codec</PackageProjectUrl>
  </PropertyGroup>
  <PropertyGroup>
    <WarningsAsErrors>CS0114</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CueSharp" Version="1.0.1" />
    <PackageReference Include="DiscUtils" Version="0.16.13" />
    <PackageReference Include="Intervals" Version="1.2.0-alpha0021" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="20.0.15" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="\" />
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>