// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("655b7309-46a9-45a2-8e60-68cd9f7d9ec2")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Codec.Tests")]
