// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("e2c9d2b9-d0cf-b7f1-db94-c47f06e5f5a0")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Codec.Tests")]
