// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("1cfa0da5-a83b-f4b2-ae72-9e3b9437786e")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Codec.Tests")]
