// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("7f9d721c-1c2c-929a-9fe4-6d6d9ea23c5a")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Codec.Tests")]
