<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SharedAssemblyProperties.props" />
  <PropertyGroup>
    <RootNamespace>Codec</RootNamespace>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/otac0n/Codec</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET.SystemDrawing" Version="8.0.24" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.15.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Codec.Base\Codec.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>