// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("ec7df4a6-e7cd-9e10-198a-75823f740172")]
[assembly: InternalsVisibleTo("Codec.Tests")]
